### ISSUE TITLE
"logging" instead of "logger"

### ISSUE THREAD

**Issue by jbruwes** [aws/amazon-cognito-js#10]
I've got a strange error "Uncaught TypeError: c.logging is not a function". I was looking for the file "CognitoSyncDataset.js". There is root.logging instead of root.logger. It seems like an error.

283 root.logging('Deferring to .onDatasetsMerged.');
340 root.logging('Dataset should be deleted. Deferring to .onDatasetDeleted.');
343 root.logging('.onDatasetDeleted returned true, purging dataset locally.');
349 root.logging('.onDatasetDeleted returned false, cancelling sync.');

**Comment by Maunte** [comment]
I'm experiencing the same error.  Did you ever find a resolution?

**Comment by jbruwes** [comment]
No, I didn't. I simply rejected to use the CognitoSync. It's so buggy and so expensive. Nowadays I am keeping and syncing all information through S3.

**Comment by itrestian** [comment]
Thanks for bringing this up. It was fixed by the following commit:

https://github.com/aws/amazon-cognito-js/commit/8e3b690e5dbfe83f208180fc4f9e39c81ead8b96

Ionut.
