### ISSUE TITLE
Is there a plan migrate it for node.js/io.js

### ISSUE THREAD

**Issue by EricCat** [aws/amazon-cognito-js#13]
Is there a plan migrate it for node.js/io.js

**Comment by turacma** [comment]
Thanks for your interest. Most of our high level SDKs are built for client applications on a mobile device or in the browser. Could you tell us about your use case for using the sync library from a node.js application?

**Comment by EricCat** [comment]
Thanks @turacma .
My use case is that I want to automate create cognito datasets by aws cli or nodejs sdk. 
As the following steps:
1. auto generate IdentityPoolId by aws cli tool  (done)
2. auto create datasets (blocking by this issue)
3. auto create records

**Comment by turacma** [comment]
This SDK is probably overkill for what you want because it maintains local state. You can access the low level APIs directly from either the Node.JS SDK or AWS CLI.

**Comment by EricCat** [comment]
@turacma  thanks very much
