### ISSUE TITLE
"new AWS.CognitoIdentityCredentials" resets IdentityId to null when there is no connection (offline)

### ISSUE THREAD

**Issue by kest85** [aws/amazon-cognito-js#17]
While connected to internet everything works fine. Problem appears when there is no connection.

```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: COGNITO_IDENTITY_POOL_ID
    });
```
This line of code resets identityId to null, so openOrCreateDataset is unable to open dataset. After that, when internet connection is available again, new identityId is assigned, so openOrCreateDataset creates new dataset instead of opening existing dataset, which was created with old identityId.

Is this a bug? if so, it looks like a critical one - whole offline functionality becomes unusable, because it is not possible to open existing dataset without having identityId (also when online new identityId makes old dataset not accessible).

Could anyone help me solve this problem?

**Comment by leecrossley** [comment]
I can confirm this same issue

**Comment by shankar-mahesh** [comment]
We are also facing same issue

**Comment by lohsie** [comment]
Same issue here!

**Comment by andrewgoodnz** [comment]
Also having this issue... Any updates or workarounds yet?

**Comment by vasanthns** [comment]
We are facing the same issue,, IdntityID is returned as null in offline mode. Any workaround would be relaly helpful..

thanks!

**Comment by itrestian** [comment]
Hi guys,

We are working on a fix for this that we plan to release shortly.

Ionut.

**Comment by andrewgoodnz** [comment]
@itrestian I realise it can be difficult to give a definitive timeframe but are we talking days, weeks or months for a fix to be released?

**Comment by sergiomilici** [comment]
any updates on this?

**Comment by itrestian** [comment]
Thanks to everyone for the patience!
This has been fixed by the following pull request so it should work in AWS SDK v2.4.4
https://github.com/aws/aws-sdk-js/pull/1028

**Comment by neosekar** [comment]
Cognito sync while offline access in javascript sdk, 
**AWS.config.credentials.get(function(err) {});**  this method returns **Network failure error**

**Comment by johnborges** [comment]
I'm experiencing the same. Is this expected?

**Comment by johnborges** [comment]
@swaminathane. The issue you mentioned has been fixed in the latest commit on the master branch of [aws-sdk-js](https://github.com/aws/aws-sdk-js).
