### ISSUE TITLE
register user with same email

### ISSUE THREAD

**Issue by GuerkanDemirci** [aws/amazon-cognito-js#23]
Bug?

I can register two different users with identical email even so email is used as an alias.

**Comment by kushwahavinay** [comment]
I am assuming this question is related to the Cognito User pools feature. 
Alias gets created once a user account is confirmed. First account which gets confirmed will have the alias and if you try to confirm the next account it will throw an exception. 
You can find more details here: http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-settings.html

You can create user pool related questions here: https://github.com/aws/amazon-cognito-identity-js/issues
