### ISSUE TITLE
Error: Synchronize failed: exceeded maximum retry count.

### ISSUE THREAD

**Issue by mgoria** [aws/amazon-cognito-js#34]
I'm receiving this error after I set  `onDatasetsMerged` callback to return `true`, and according to README.md it should `continue the synchronization process`:

```
dataset.synchronize({
  // ...

  onDatasetsMerged: (dataset, datasetNames, callback) => {
    return callback(true);
  }
});
```

Can someone help me understand how `onDatasetsMerged` method works, should I write the logic to merge datasets or it's merged automatically ?

A basic code snippet would be much appreciated :)

Thanks!

**Comment by itrestian** [comment]
Hi!

See answer below on the cases when onDatasetsMerged will be called:

https://forums.aws.amazon.com/thread.jspa?threadID=179708

Ionut.

**Comment by mgoria** [comment]
@itrestian Thanks, I'll take a look.
