### ISSUE TITLE
Need clarification on CognitoIdentityCredentials, and issue with AWS.config.region?

### ISSUE THREAD

**Issue by homingli** [aws/amazon-cognito-js#5]
(1) From the README here:
```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    AccountId: 'YOUR AWS ACCOUNT ID',
    IdentityPoolId: 'YOUR IDENTITY POOL ID',
    RoleArn: 'YOUR UNAUTHENTICATED ROLE ARN'
});
```

... contradicts with ... 

(2) Documentation: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html
```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: 'YOUR IDENTITY POOL ID',
  Logins: { // optional tokens, used for authenticated login
    'graph.facebook.com': 'FBTOKEN',
    'www.amazon.com': 'AMAZONTOKEN',
    'accounts.google.com': 'GOOGLETOKEN'
  }
});
```

I think I go it working with (2). However, as Cognito is only available in us-east-1 and not us-west-2, with my resources in us-west-2, I define AWS.config.region = 'us-west-2' for other calls, I then get the error: 
`OPTIONS https://cognito-identity.us-west-2.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED`

Is the README here outdated?
Should Cognito not rely on AWS.config.region?

How should I go about communicating with Cognito in us-east-1, while making other AWS API calls to us-west-2?

**Comment by chetanme** [comment]
Thanks for bringing these issues to our attention. The README is indeed outdated and you should use the constructor from the documentation.

We use the AWS.config.region to contact Cognito and currently there is no way to override the region specification to contact Cognito while using any other region in your global settings.

We will work on addressing these issues in our next release cycle.

Regards,
Chetan

**Comment by levithomason** [comment]
This issue looks like it was resolved by 8599ec1a0252ccc3a725f49a58bfd6612875e995, yea?

**Comment by chetanme** [comment]
Yes. We fixed the reported bug.

**Comment by levithomason** [comment]
You may want to close this issue, so it doesn't look like it's an open bug ;) 

I've posted an issue about maintenance and helping out, #11.  That'd be great if you could take a look there, too.
