### ISSUE TITLE
Using amazon-cognito-js in Lambda Function

### ISSUE THREAD

**Issue by Leon-Africa** [aws/amazon-cognito-js#55]
I uploaded zip file containing the module in Lambda function.

After doing AWS Cognito Logins map I get AWS Keys from sts, that works fine.

The issue is when I instantiate the Cognito Sync manager with:

var client = new AWS.CognitoSyncManager();

I get the following error:

<img width="879" alt="screen shot 2017-09-07 at 11 30 05 am" src="https://user-images.githubusercontent.com/16097992/30156612-668e6e00-93c0-11e7-9c81-4b37366efb3d.png">

It seems that this package will only work in browser?  How can I use this package in Lambda Function?

**Comment by Leon-Africa** [comment]
I un-minified the js file and uploaded the file getting the following:

<img width="862" alt="screen shot 2017-09-07 at 11 46 58 am" src="https://user-images.githubusercontent.com/16097992/30157356-62ad9458-93c2-11e7-988c-45ce7f3c0222.png">


At line 607 code is:

 AWS = AWS || {}, AWS.CognitoSyncManager = AWS.CognitoSyncManager || {}, AWS.CognitoSyncManager.StoreLocalStorage = function() {
        var a = function() {
            this.store = window.localStorage
        };

This is where Lambda is throwing the error.

**Comment by zootopia106** [comment]
I am also faced with this error.

**Comment by itrestian** [comment]
There's a note on the repo "This library is designed to run in the browser. It has not been tested for use in other environments." 

Window and local storage which are used for storing data are only available in a browser environment.
